# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcb04b0251ae2cf96e759f364b94fd8599933d96ad8b458f362d2528bc3359dfb67f74997bc8392dabf97ff6b65bb554f417ec98b2d245d258e19720ecd17d68

test:
  secret_key_base: ff3c39b6ebbe2cad42638fdd3dba2becb342cf2d07a3709c518547140ef04f9e75602117972aba047482b97aaf78ff41edf381340fc99076b059ce96edfe5d0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
